export const FETCH_SUB = 'FETCH_SUB';
export const LOAD_SUB_POSTS = 'LOAD_SUB_POSTS';
export const TOGGLE_SUBPAGE_VOTE = 'TOGGLE_SUBPAGE_VOTE';
export const SUBSCRIBE_SUB = 'SUBSCRIBE_SUB';
export const EDIT_DESCRIPTION = 'EDIT_DESCRIPTION';
